name: Build And Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'pages/**'
      - 'package.json'
      - '.vitepress/**'

permissions: 
  contents: write

env:
  TZ: Asia/Shanghai
  VITE_GISCUS_REPO_ID: ${{ secrets.VITE_GISCUS_REPO_ID }}
  VITE_GISCUS_CATEGORY_ID: ${{ secrets.VITE_GISCUS_CATEGORY_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build
        run: npm i && npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: yqchilde/yy-notes
          BRANCH: gh-pages
          FOLDER: dist

  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Crawler Automatic Crawl
        needs: deploy
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.0
        env:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-name: 'yqqy'
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://yqqy.top'
